version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./env_files/DB.env

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./env_files/DJANGO_CONFIG.env
    depends_on:
      - db
