version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=djangopassword
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=djangopassword
        # Possible values: *.dev | *.prd
      - DJANGO_SETTINGS_MODULE=api_core.settings.dev
    depends_on:
      - db
